[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  # Force Node.js build
  NPM_CONFIG_PYTHON = "false"
  NPM_CONFIG_IGNORE_SCRIPTS = "false"

# Explicitly specify this is a Node.js project
[build.processing]
  skip_processing = false

# Prevent Python dependency installation
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Force npm install instead of pip
[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
